### ISSUE TITLE
Suppress wildfly-maven-plugin executions when tests are skipped

### ISSUE THREAD

**Issue by djcoleman** [wildfly-extras/fuse-patch#141]
If I build fuse-patch with the skipTests property set to true, some of the plugins in the itests/jaxws pom are still run. Is it possible to change this so that the plugins running in the process-test-sources and process-test-resources are also skipped?

**Comment by tdiesler** [comment]
The tests are skipped

```
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ fuse-patch-itests-jaxws ---
[INFO] Tests are skipped.
```
