### ISSUE TITLE
Migrate to Galleon

### ISSUE THREAD

**Issue by ppalaga** [wildfly-extras/fuse-patch#195]
Galleon is the new provisioning mechanism of WildFly that will replace the current feature packs. Based on this http://lists.jboss.org/pipermail/wildfly-dev/2018-June/006573.html message on wildfly-dev list, we should start migrating from FPs to Galleon.

**Comment by tdiesler** [comment]
In fact and if possible we should retire fuse-patch for wildfly-camel and fuse-eap. IIRC, feature packs are used to provision the test servers. There is a fuse-eap installer, that uses uses fuse-patch to install the wfc distro and then runs some post-install actions that use DOM ops to tweak the config.

Do you already have a proposed migration plan?

CrossRef: https://github.com/wildfly-extras/wildfly-camel/issues/2560

**Comment by ppalaga** [comment]
> In fact and if possible we should retire fuse-patch for wildfly-camel and fuse-eap. 

Yes, I am all for dissolving fuse-patch.

> IIRC, feature packs are used to provision the test servers. 

Yes and in the future, galleon packs can be used to provision any server, not just test server.

> There is a fuse-eap installer, that uses uses fuse-patch to install the wfc distro and then runs some post-install actions that use DOM ops to tweak the config.

Not sure why you are saying this.

> Do you already have a proposed migration plan?

Migration plan of what? I am working on migrating the old feature packs to Galleon packs, the criterion of success being that the itests pass with the new Galleon packs. I have no plans to do anything else.

CrossRef: wildfly-extras/wildfly-camel#2560

**Comment by tdiesler** [comment]
Why do we need to make changes to this project, if the goal is to migrate wfc + fuse-eap away from it?

**Comment by ppalaga** [comment]
I see the scope of this issue as containing solely the migration of the existing FPs to Galleon. Both Galleon and the fuse patching tool are new to me. It is safer to do one after another.

**Comment by tdiesler** [comment]
Sure, and this can be done privately in whatever ways it may. This project however, should not need to move toward galleon.

**Comment by ppalaga** [comment]
There is a legacy fuse-patch FP that WFC FPs depend on. To be able to migrate those, I first need to migrate this one. BTW, the work has been done for fuse-patch already. See https://github.com/wildfly-extras/fuse-patch/commits/wildfly-14.x-proposed

**Comment by tdiesler** [comment]
Won't do
